Click the Applications icon on the left menu bar.
Click Settings, then Network.
Find your internet connection on the right pane, then click the gear icon.
Click the IPv4 or IPv6 tab to view your DNS settings.
Set the “Automatic” toggle on the DNS entry to Off.
Provide the 1.1.1.1 DNS addresses in the DNS entries field:
For IPv4: 1.1.1.1 and 1.0.0.1
For IPv6: 2606:4700:4700::1111,2606:4700:4700::1001
Click Apply, then restart your browser.
You’re all set! Your device now has faster, more private DNS servers ✌️✌️
