# ~/.config/starship.toml

# Specify the palette to use
palette = "ayu-dark"

# Define the custom palette colors
[palettes.ayu-dark]
black   = "#0f1419"
base    = "#14191f"
surface = "#191e2a"
overlay = "#242936"
muted   = "#3e4b59"
subtle  = "#5c6773"
text    = "#e6b450" 
fg      = "#f07178" 
red     = "#ff3333"
orange  = "#ff7733"
yellow  = "#e6b450"
green   = "#7fd962"
cyan    = "#95e6cb"
blue    = "#39bae6"
purple  = "#f29718"
magenta = "#f07178"

# Settings for modules
[cmd_duration]
disabled = true

[time]
disabled = true

[character]
# Here, "green" and "red" refer to the keys defined in [palettes.flexoki-dark]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Example: If you want to use other colors from your palette elsewhere:
[directory]
style = "bold italic orange"
format = "[$path](bold italic orange)[$read_only]($read_only_style) "
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
read_only_style = "bold yellow"
truncate_to_repo = true

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

#[directory]
#read_only = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)" 
modified = "[${count}+](yellow)" 
deleted =  "[${count}-](red)" 
conflicted =  "[${count}~](red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)" 
staged = "[${count}+](green)" 

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"	
revert = "revert"	
cherry_pick = "cherry"
bisect = "bisect"	
am = "am"	
am_or_rebase = "am/rebase"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = "🐍 "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

